
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS'

export const RECEIVE_ITEM = 'RECEIVE_ITEM'

export const RECEIVE_GENRES = 'RECEIVE_GENRES'
export const RECEIVE_GENRE_ID = 'RECEIVE_GENRE_ID'

export const RECEIVE_BAND_ID = 'RECEIVE_BAND_ID'
export const RECEIVE_BANDS = 'RECEIVE_BANDS'

export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'
